### ISSUE TITLE
Scroll issue with Safari in NoCode builder

### ISSUE THREAD

**Issue by NickAtGit** [qonversion/no-codes-ios#16]
<img width="947" alt="Image" src="https://github.com/user-attachments/assets/98d803a4-29bc-4cc0-8b6e-4e18c5ebe219" />

When scrolling through the list of products and then through the variables is quite difficult in Safari. The scrolling stops and can often not be continued. In Chrome it works fine, but I have lot's of reasons not to use Chrome.

**Comment by suriksarkisyan** [comment]
Hi. As I mentioned in the adjacent issue, I will pass this on to the responsible team and will get in touch with you as soon as there is a fix.

**Comment by suriksarkisyan** [comment]
Hello, @NickAtGit . Could you please check again? We have released a fix.

**Comment by NickAtGit** [comment]
Unfortunately the scroll issue is still there `Safari Version 18.4 (20621.1.15.11.10), macOS 15.4.1 (24E263)`
